name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: android-actions/setup-android@v3
    - run: |
        unzip Kurdistan-Keyboard.zip
        cd Kurdistan
        sed -i 's/gradle-8.0/gradle-8.5/g' gradle/wrapper/gradle-wrapper.properties
        chmod +x gradlew
        ./gradlew assembleDebug --warning-mode none
    - uses: actions/upload-artifact@v4
      with:
        name: Kurdistan-APK
        path: Kurdistan/app/build/outputs/apk/debug/app-debug.apk
